steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute scp index.php ${_GCE_INSTANCE}:/var/www/html/ \
          --zone=${_GCE_ZONE} \
          --project=$PROJECT_ID \
          --quiet

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _GCE_INSTANCE: 'gce-sample'
  _GCE_ZONE: 'asia-northeast1-a'
